./rtl/Clk_ctrl.v
./rtl/MAC_rx.v
./rtl/MAC_top.v
./rtl/MAC_tx.v
./rtl/Phy_int.v
./rtl/RMON.v
./rtl/eth_miim.v
./rtl/header.v
./rtl/reg_int.v
./rtl/MAC_rx/CRC_chk.v
./rtl/MAC_rx/Broadcast_filter.v
./rtl/MAC_rx/MAC_rx_FF.v
./rtl/MAC_rx/MAC_rx_add_chk.v
./rtl/MAC_rx/MAC_rx_ctrl.v
./rtl/RMON/RMON_addr_gen.v
./rtl/RMON/RMON_ctrl.v
./rtl/RMON/RMON_dpram.v
./rtl/TECH/CLK_DIV2.v
./rtl/TECH/CLK_SWITCH.v
./rtl/TECH/afifo.v
./rtl/TECH/duram.v
./rtl/MAC_tx/CRC_gen.v
./rtl/MAC_tx/MAC_tx_Ctrl.v
./rtl/MAC_tx/MAC_tx_FF.v
./rtl/MAC_tx/MAC_tx_addr_add.v
./rtl/MAC_tx/Ramdon_gen.v
./rtl/MAC_tx/flow_ctrl.v
./rtl/miim/eth_clockgen.v
./rtl/miim/eth_outputcontrol.v
./rtl/miim/eth_shiftreg.v
./rtl/miim/timescale.v
./dut/tb_mac.sv
./dut/clk_gen.v
./dut/user_interface.v
./dut/host_interface.v
./dut/phy_interface.v
